'use strict';
const $=id=>document.getElementById(id), c=$('scene'), ctx=c.getContext('2d');
let box={x1:400,y1:250,x2:600,y2:350}, photo=null, filename='sample', start=null, valid=true;
function normalize(b,W,H){return [((b.x1+b.x2)/2)/W,((b.y1+b.y2)/2)/H,(b.x2-b.x1)/W,(b.y2-b.y1)/H];}
for(const k of ['x1','y1','x2','y2']){const l=document.createElement('label');l.textContent=k+' ';const i=document.createElement('input');i.type='number';i.id=k;i.min=0;i.step=1;i.value=box[k];i.addEventListener('input',()=>{box[k]=Number(i.value);update(false)});l.append(i);$('fields').append(l);}
function sample(){c.width=1000;c.height=1000;photo=null;filename='sample';box={x1:400,y1:250,x2:600,y2:350};$('class').value='0';$('upload').value='';update(true);}
function render(){ctx.clearRect(0,0,c.width,c.height);if(photo){ctx.drawImage(photo,0,0)}else{ctx.fillStyle='#e9eff1';ctx.fillRect(0,0,1000,1000);ctx.fillStyle='#c8d7d7';ctx.fillRect(0,440,1000,560);ctx.fillStyle='#365e72';ctx.fillRect(200,170,600,260);ctx.fillStyle='#8fc6d7';ctx.fillRect(285,185,430,55);ctx.fillStyle='#102e40';ctx.fillRect(235,415,90,100);ctx.fillRect(675,415,90,100);ctx.fillStyle='#fff4d1';ctx.fillRect(400,250,200,100);ctx.fillStyle='#102e40';ctx.font='bold 21px system-ui';ctx.fillText('TN 09 AB 1234',420,309);ctx.fillStyle='#617a85';ctx.font='24px system-ui';ctx.fillText('Synthetic illustration • 1000 × 1000',250,820);}
const s=Math.max(c.width,c.height)/1000;ctx.strokeStyle='#008c77';ctx.lineWidth=4*s;ctx.strokeRect(box.x1,box.y1,box.x2-box.x1,box.y2-box.y1);ctx.fillStyle='#00a787';ctx.beginPath();ctx.arc((box.x1+box.x2)/2,(box.y1+box.y2)/2,6*s,0,Math.PI*2);ctx.fill();ctx.font=`${20*s}px system-ui`;ctx.fillText(`(${$('x1').value}, ${$('y1').value})`,box.x1,Math.max(22*s,box.y1-10*s));}
function update(sync){if(sync)for(const k in box)$(k).value=Math.round(box[k]);$('dims').textContent=`Original image: ${c.width} × ${c.height} pixels. Green dot = box centre.`;valid=Object.values(box).every(Number.isFinite)&&box.x1>=0&&box.y1>=0&&box.x2<=c.width&&box.y2<=c.height&&box.x2>box.x1&&box.y2>box.y1;$('error').textContent=valid?'':'Use a positive-area box fully inside the image.';$('download').disabled=!valid;if(valid){const n=normalize(box,c.width,c.height);$('label').textContent=$('class').value+' '+n.map(v=>v.toFixed(6)).join(' ');$('math').textContent=`Centre = (${((box.x1+box.x2)/2).toFixed(1)}, ${((box.y1+box.y2)/2).toFixed(1)}) px. Size = ${(box.x2-box.x1).toFixed(1)} × ${(box.y2-box.y1).toFixed(1)} px.`;}else{$('label').textContent='Invalid bounding box';$('math').textContent='';}render();}
function point(e){const r=c.getBoundingClientRect();return{x:Math.round(Math.max(0,Math.min(c.width,(e.clientX-r.left)*c.width/r.width))),y:Math.round(Math.max(0,Math.min(c.height,(e.clientY-r.top)*c.height/r.height)))};}
c.addEventListener('pointerdown',e=>{start=point(e);c.setPointerCapture(e.pointerId)});c.addEventListener('pointermove',e=>{if(!start)return;const p=point(e);box={x1:Math.min(start.x,p.x),y1:Math.min(start.y,p.y),x2:Math.max(start.x,p.x),y2:Math.max(start.y,p.y)};update(true)});c.addEventListener('pointerup',()=>{start=null});c.addEventListener('pointercancel',()=>{start=null});$('sample').onclick=sample;$('class').onchange=()=>update(false);
let loadSerial=0;$('upload').onchange=e=>{const f=e.target.files[0];if(!f)return;const serial=++loadSerial, url=URL.createObjectURL(f),im=new Image();im.onload=()=>{URL.revokeObjectURL(url);if(serial!==loadSerial)return;photo=im;c.width=im.naturalWidth;c.height=im.naturalHeight;filename=f.name.replace(/\.[^.]+$/,'');box={x1:Math.round(c.width*.25),y1:Math.round(c.height*.25),x2:Math.round(c.width*.75),y2:Math.round(c.height*.75)};update(true)};im.onerror=()=>{URL.revokeObjectURL(url);$('error').textContent='This file could not be decoded as an image.'};im.src=url};
$('download').onclick=()=>{if(!valid)return;const url=URL.createObjectURL(new Blob([$('label').textContent+'\n'],{type:'text/plain'}));const a=document.createElement('a');a.href=url;a.download=filename+'.txt';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};
const tc=$('track'), tctx=tc.getContext('2d');let playing=false,last=0;
function track(){const f=Number($('frame').value),x=40+f*6.5;tctx.fillStyle='#e9eff1';tctx.fillRect(0,0,900,280);tctx.fillStyle='#cedbde';tctx.fillRect(0,190,900,90);tctx.strokeStyle='#de864a';tctx.lineWidth=3;tctx.beginPath();tctx.moveTo(450,0);tctx.lineTo(450,280);tctx.stroke();tctx.fillStyle='#315e73';tctx.fillRect(x,100,130,95);tctx.strokeStyle='#008c77';tctx.strokeRect(x-8,85,146,120);tctx.fillStyle='#007c73';tctx.font='20px system-ui';tctx.fillText('Vehicle • ID 17',x-8,72);$('trackinfo').textContent=`Simulated frame ${f} / 100. Centre x = ${(x+65).toFixed(0)} px. ${x+65>=450?'Past the counting line.':'Approaching the counting line.'}`;}
$('frame').oninput=track;$('play').onclick=()=>{playing=!playing;};function tick(now){if(playing&&now-last>65){$('frame').value=(Number($('frame').value)+1)%101;track();last=now;}requestAnimationFrame(tick)}sample();track();requestAnimationFrame(tick);
function inspector(){const W=c.width,H=c.height,N=Number($('inputsize').value),r=Math.min(N/W,N/H),px=(N-W*r)/2,py=(N-H*r)/2;$('inspect').textContent=`Image: ${W} × ${H}; ${(W*H/1e6).toFixed(2)} megapixels; aspect ratio ${(W/H).toFixed(3)}. ${valid?`Box: ${(box.x2-box.x1).toFixed(0)} × ${(box.y2-box.y1).toFixed(0)} pixels; area ${((box.x2-box.x1)*(box.y2-box.y1)).toFixed(0)} px² (${(100*(box.x2-box.x1)*(box.y2-box.y1)/(W*H)).toFixed(2)}% of image).`:''}`;$('letterbox').textContent=`Input ${N} × ${N}: scale ${r.toFixed(4)}, content ${(W*r).toFixed(1)} × ${(H*r).toFixed(1)}, padding per side x=${px.toFixed(1)}, y=${py.toFixed(1)}. ${valid?`Transformed box: (${(box.x1*r+px).toFixed(1)}, ${(box.y1*r+py).toFixed(1)})–(${(box.x2*r+px).toFixed(1)}, ${(box.y2*r+py).toFixed(1)}).`:''}`;}
const originalUpdate=update;update=function(sync){originalUpdate(sync);inspector()};$('inputsize').onchange=inspector;inspector();
